#!/usr/bin/make -f
# Makefile for sve-template-plugin.lv2 #
# ----------------------- #
# Created by StevenRVE
#

# --------------------------------------------------------------
# Project name, used for binaries

NAME = sve-template-plugin

# --------------------------------------------------------------
# Files to build

OBJS_DSP = \
	template-plugin.cpp.o \

# --------------------------------------------------------------
# Do some magic

include Makefile.mk

# --------------------------------------------------------------
